# config file for Twitter API keys

api_key: 2TgYyWEoI1SyqcRwt6sAN4J31
api_secret_token: vz5X5mffKF4ZOKSqRqLRHsuYXH1hGZ1PBLJSGwi73CTlOP2HkP
access_token: 102265639-WKuC5i5Lh6RzsPidKKgdEswCw9Md9WBlHMDFrRPE
access_token_secret: dZOnOv41lkKnabmyE6yB7sSZLPllqAiJpEnhoUqWhtjPS 
